import { Inter } from "next/font/google";
// import "./globals.css";

//Styles
import "bootstrap/dist/css/bootstrap.min.css";
// componentes
import { BotonToast } from "./components/BotonToast";
import Example from "./components/BotonModal";
import Example2 from "./components/Carousel";

//METADATOS
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        {children}
        <BotonToast />
        <Example/>
        <Example2/>
      </body>
    </html>
  );
}
